[package]
name = "djvu_encoder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
roxmltree = "0.18"
regex = "1.10"
once_cell = "1.19"
image = "0.24"
byteorder = "1.5"
flate2 = "1.0"
thiserror = "1.0"
bytemuck = { version = "1.14", features = ["derive"] }
bzip2 = "0.4"
tracing = "0.1"
tracing-subscriber = "0.3"
bitflags = "2.0"
libc = "0.2"
url = "2.0"
rayon = "1.0"
log = "0.4"
lazy_static = "1.4.0"
lutz = "1.4"
bitvec = "1.0"

[dev-dependencies]
tempfile = "3.10"